version: '3.7'
services:
  db:
    image: mysql:8
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=your_db
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_HOST=db
    ports:
      - "3307:3306"
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8081:8080"
    restart: unless-stopped